local GameManager = require("scenes.game_manager")

local function switch_to_scene(new_scene)

	if GameManager.current_level == "menu" then
		msg.post("#menu", "unload")
	elseif GameManager.current_level == "controls" then
		msg.post("#controls", "unload")
	elseif GameManager.current_level == "level" then
		msg.post("#level", "unload")
	end

	GameManager.current_level = new_scene

	if new_scene == "menu" then
		msg.post("#menu", "load")
	elseif new_scene == "controls" then
		msg.post("#controls", "load")
	elseif new_scene == "level" then
		msg.post("#level", "load")
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")

	GameManager.current_level = "menu"
	msg.post("#menu", "load")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
	end

	if message_id == hash("proxy_unloaded") then
		print("Unloaded:", sender)
	end

	if message_id == hash("change_scene") and message.scene then
		switch_to_scene(message.scene)
	end

	if message_id == hash("toggle_sound") then
		GameManager.is_sound_on = not GameManager.is_sound_on
	end
end

function on_input(self, action_id, action)

	if action_id == hash("key_scape") then
		sys.exit(0)
	end
	
	if action_id == hash("Tab") and action.released then
		if GameManager.current_level == "level" then
			switch_to_scene("menu")
		end
	end
end
