local frequency = 0.5
local gem1_prob = 0.2
local min_x = 40
local max_x = 560

function init(self)
	self.timer = 1/frequency
	math.randomseed(0)
end

function update(self, dt)
	self.timer = self.timer - dt
	
	if self.timer <= 0 then
		
		self.timer = 1/frequency
		local position = go.get_position()
		position.x = vmath.lerp(math.random(), min_x, max_x)
		position.y = 500
		print("x: " .. position.x .. "y: " .. position.y )
		local component = "#star_factory"

		if math.random() < gem1_prob then
			component = "#gem1_factory"
		end
		factory.create(component, position)
	end
end