local max_speed = 300
local min_x = 40
local max_x = 560
local min_y = 40
local max_y = 460

function init(self)
	msg.post(".", "acquire_input_focus")
	self.speed_x = 0
	self.speed_y = 0
	self.left_pressed = false
	self.right_pressed = false
	self.up_pressed = false
	self.down_pressed = false
end

function update(self, dt)
	local position = go.get_position()
	position.x = position.x + self.speed_x * dt
	position.y = position.y + self.speed_y * dt
	
	-- Screen limits
	position.x = math.max(min_x, math.min(position.x, max_x))
	position.y = math.max(min_y, math.min(position.y, max_y))

	go.set_position(position)
end

function on_input(self, action_id, action)
	
	if action_id == hash("left") then
		
		if action.pressed then
			self.left_pressed = true
			sprite.play_flipbook("#sprite", "turn_left_idle")
		elseif action.released then
			self.left_pressed = false
			sprite.play_flipbook("#sprite", "idle")
		end
		
	elseif action_id == hash("right") then
		
		if action.pressed then
			self.right_pressed = true
			sprite.play_flipbook("#sprite", "turn_right_idle")
		elseif action.released then
			self.right_pressed = false
			sprite.play_flipbook("#sprite", "idle")
		end
		
	elseif action_id == hash("up") then

		if action.pressed then
			self.up_pressed = true
			sprite.play_flipbook("#sprite", "idle")
		elseif action.released then
			self.up_pressed = false
			sprite.play_flipbook("#sprite", "idle")
		end

	elseif action_id == hash("down") then

		if action.pressed then
			self.down_pressed = true
			sprite.play_flipbook("#sprite", "idle")
		elseif action.released then
			self.down_pressed = false
			sprite.play_flipbook("#sprite", "idle")
		end
			
	elseif action_id == hash("key_space") and action.pressed then
		local player_position = go.get_position()
		player_position.y = player_position.y + 10

		local bullet_id = factory.create("#bullet1_factory", player_position)
		local distance = 500
		local speed = 800
		local duration = distance / speed
		local to = player_position.y + distance

		go.animate(bullet_id, "position.y", go.PLAYBACK_ONCE_FORWARD, to, go.EASING_LINEAR, duration, 0, function()
			go.delete(bullet_id)
		end)
	end

	self.speed_x = 0
	self.speed_y = 0

	if self.left_pressed then
		self.speed_x = self.speed_x - max_speed
	end

	if self.right_pressed then
		self.speed_x = self.speed_x + max_speed
	end

	if self.up_pressed then
		self.speed_y = self.speed_y + max_speed
	end

	if self.down_pressed then
		self.speed_y = self.speed_y - max_speed
	end
end