local max_speed = 300
local min_x = 40
local max_x = 560

function init(self)
	msg.post(".", "acquire_input_focus")
	self.speed = 0
end

function update(self, dt)
	local position = go.get_position()
	position.x = position.x + self.speed * dt

	if position.x <= min_x then
		position.x = min_x
	elseif position.x >= max_x then
		position.x = max_x
	end

	go.set_position(position)

	self.speed = 0
end

function on_input(self, action_id, action)
	-- horizontal movement
	if action_id == hash("left") then
		self.speed = -max_speed
	elseif action_id == hash("right") then
		self.speed = max_speed
	elseif action_id == hash("key_space") and action.pressed then
		print("shoot")
		local player_position = go.get_position()
		player_position.y = player_position.y + 10

		local bullet_id = factory.create("#bullet1_factory", player_position)

		local distance = 1000
		local speed = 800
		local duration = distance/speed
		local to = player_position.y + distance

		go.animate(bullet_id, "position.y", go.PLAYBACK_ONCE_FORWARD, to, go.EASING_LINEAR, duration, 0, function()
			go.delete(bullet_id)
		end)
	end
end















