local GameManager = require("_Scripts.GameManager")

local function update_sound_icon(is_on)
	-- local texture = is_on and "SoundOn" or "SoundOff"
	-- gui.play_flipbook(gui.get_node("Image"), texture)
	-- sound.pause("/Music#sound", not is_on) 
end

function init(self)
	-- self.sound_box = gui.get_node("SoundBox")
	-- self.sound_icon = gui.get_node("Image")

	self.start_button = gui.get_node("StartButton")
	self.exit_button = gui.get_node("ExitButton")

	msg.post(".", "acquire_input_focus")

	-- sound.play("/Music#sound", {delay = 1, gain = 0.05, pan = 0, speed = 1.0})

	-- update_sound_icon(GameManager.is_sound_on)
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		-- if gui.pick_node(self.sound_box, action.x, action.y) then
		--	print("Sound toggle clicked!")
		--	GameManager.is_sound_on = not GameManager.is_sound_on
		--	update_sound_icon(GameManager.is_sound_on)
		-- end

		if gui.pick_node(self.start_button, action.x, action.y) then
			print("Start button clicked!")
			msg.post("main:/SceneParent", "change_scene", { scene = "level" })
		end

		if gui.pick_node(self.exit_button, action.x, action.y) then
			print("Exit button clicked!")
			os.exit()
		end
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("update_sound_icon") and message.sound_on ~= nil then
		update_sound_icon(message.sound_on)
	end
end
