local GameManager = require("_Scripts.GameManager")

local function switch_to_scene(new_scene)
	if new_scene == "level" then
		GameManager.current_level = new_scene
		msg.post("#menu", "unload")
		msg.post("#level", "load")
	elseif new_scene == "menu" then
		GameManager.current_level = new_scene
		msg.post("#level", "unload")
		msg.post("#menu", "load")
	end
end

function init(self)
	msg.post(".", "acquire_input_focus")
	msg.post("#menu", "load")
end

function on_message(self, message_id, message, sender)
	if message_id == hash("proxy_loaded") then
		msg.post(sender, "enable")
	end

	if message_id == hash("change_scene") and message.scene then
		switch_to_scene(message.scene)
	end

	if message_id == hash("toggle_sound") then
		GameManager.is_sound_on = not GameManager.is_sound_on
	end
end

function on_input(self, action_id, action)
	if action_id == hash("Tab") and action.released then
		if GameManager.current_level == "level" then
			switch_to_scene("menu")
		end
	end
end
