local utils = require("utils.animation")

local max_speed = 300
local min_x = 40
local max_x = 560
local min_y = 40
local max_y = 460
local player_on_ship = false

function init(self)
	msg.post(".", "acquire_input_focus")
	self.left_pressed = false
	self.right_pressed = false
	self.up_pressed = false
	self.down_pressed = false
end

function update(self, dt)

	if not player_on_ship then 
		return 
	end

	-- DIRECTION
	local direction = vmath.vector3()

	if self.left_pressed then
		direction.x = direction.x - 1
	end

	if self.right_pressed then
		direction.x = direction.x + 1
	end

	if self.up_pressed then
		direction.y = direction.y + 1
	end

	if self.down_pressed then
		direction.y = direction.y - 1
	end

	-- Normalize the direction vector to prevent faster diagonal movement.
	if vmath.length_sqr(direction) > 0 then
		direction = vmath.normalize(direction)
	end

	-- POSITION
	local position = go.get_position()
	local movement = direction * max_speed * dt
	position = position + movement
	
	-- Screen limits
	position.x = math.max(min_x, math.min(position.x, max_x))
	position.y = math.max(min_y, math.min(position.y, max_y))

	-- ANIMATIONS
	if self.left_pressed then
		utils.play_animation(self, "turn_left_idle")
	elseif self.right_pressed then
		utils.play_animation(self, "turn_right_idle")
	else
		utils.play_animation(self, "idle")
	end
	
	go.set_position(position)
end

function on_input(self, action_id, action)
	
	if action_id == hash("key_left") then
		
		if action.pressed then
			self.left_pressed = true
		elseif action.released then
			self.left_pressed = false
		end
		
	elseif action_id == hash("key_right") then
		
		if action.pressed then
			self.right_pressed = true
		elseif action.released then
			self.right_pressed = false
		end
		
	elseif action_id == hash("key_up") then

		if action.pressed then
			self.up_pressed = true
		elseif action.released then
			self.up_pressed = false
		end

	elseif action_id == hash("key_down") then

		if action.pressed then
			self.down_pressed = true
		elseif action.released then
			self.down_pressed = false
		end
			
	elseif action_id == hash("key_space") and action.pressed then
		local player_position = go.get_position()
		player_position.y = player_position.y + 10

		local bullet_id = factory.create("#bullet1_factory", player_position)
		local distance = 500
		local speed = 800
		local duration = distance / speed
		local to = player_position.y + distance

		go.animate(bullet_id, "position.y", go.PLAYBACK_ONCE_FORWARD, to, go.EASING_LINEAR, duration, 0, function()
			go.delete(bullet_id)
		end)
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("player_on_ship") then
		player_on_ship = true
	end
end



